### PR TITLE
Maxim update

### PR DESCRIPTION
**Pull request by buddhasystem**
Additions:
- Initial version of the unit tests, one (simple) for the battery, with the age factor added and a few cycles
- A "sim" test which for now is checking the panel power output at a few discrete points in time, like a regression test

Both will be a part of the CI when the Docker work is all done.

Corrections:
- Extraneous code and the ctor argument removed from the Battery class, API updates to match that, elsewhere
- Comtable corrected to reflect the actual 'main' condition as opposed to the previous placeholder

Documentation:
- Substantial additions to the READMEs to comply with the most recent nomenclature of devices and states, plus comments  on the content of the repo.
-

### CODE REVIEW

**Review by slosar — CHANGES_REQUESTED** [review]
This in general looks good. 
I request two changes:

 * test should look for the `LUSEEOPSIM_PATH` env variable and if set, add it to the python path (`import sys; sys.path.append`). This will minimize friction when running
 *  Tests should actually fail if the results are not what is expected -- so that CI can meaningfully fail if someone screws up somethig.

**Comment by slosar** [comment]
See all the PR I made in luseepy, where I mention the `LUSEEOPSIM_PATH`. TO review, click "files changed" on the PR, accepted and then squash merge + delete branch.  This PR is so minimal it doens't need to be really reviwed, I'm just issuing it so that you can see what I did there.

https://github.com/lusee-night/luseepy/pull/47

**Comment by buddhasystem** [comment]
Adding the env variable...

**Comment by buddhasystem** [comment]
Ready for merge?

**Review by slosar — APPROVED** [review]

**Comment by slosar** [comment]
Meriging and closing.

**Pull request merged**
